version: '3.9'

services:
  kangaroo:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/data
    working_dir: /opt/Kangaroo
    entrypoint: /bin/bash

